---
abstract: 'A script for logging into devices'
author:
  - 'Robert Drake, C<< <rdrake at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Most: 0.31
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Tel
no_index:
  directory:
    - inc
    - t
recommends:
  File::KeePass: 0
  Passwd::Keyring::Auto: 0
  Term::ANSIColor: 0
  Term::ReadKey: 0
requires:
  Expect: '0.0'
  Hash::Merge::Simple: '0.0'
  IO::Stty: '0.0'
  perl: 5.10.0
resources:
  bugtracker: https://github.com/rfdrake/tel/issues
  homepage: http://search.cpan.org/dist/App-Tel
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rfdrake/tel.git
version: '0.201001'
